### ISSUE TITLE
HTML Tables for Layout

### ISSUE THREAD

**Issue by ShahzadaMamatisaeva** [BrightBrainsKk/Section-3-Introduction-to-HTML#2]
Снять видео и загрузить

**Comment by nuranurbekova** [comment]
[section#3 Using HTML Tables for Layout.zip](https://github.com/BrightBrainsKk/Section-3-Introduction-to-HTML/files/7007050/section.3.Using.HTML.Tables.for.Layout.zip)
Посмотрела видео и сняла видео
