### ISSUE TITLE
HTML Tables Solution Walkthrough 

### ISSUE THREAD

**Issue by ShahzadaMamatisaeva** [BrightBrainsKk/Section-3-Introduction-to-HTML#6]
Загрузить код и снять видео урок.

**Comment by nuranurbekova** [comment]
[section#3 Code Challenge-HTML Tables Solution Walkthrough.zip](https://github.com/BrightBrainsKk/Section-3-Introduction-to-HTML/files/7007054/section.3.Code.Challenge-HTML.Tables.Solution.Walkthrough.zip)
Посмотрела видео и сняла видео
