### ISSUE TITLE
Forms in Practice - Create a Contact Me Form

### ISSUE THREAD

**Issue by ShahzadaMamatisaeva** [BrightBrainsKk/Section-3-Introduction-to-HTML#8]
Снять видео урок и загрузить код.

**Comment by AbdulazhanovaChynara** [comment]
[inputs.zip](https://github.com/BrightBrainsKk/Section-3-Introduction-to-HTML/files/7023115/inputs.zip)

**Comment by AbdulazhanovaChynara** [comment]
[inputs.zip](https://github.com/BrightBrainsKk/Section-3-Introduction-to-HTML/files/7023119/inputs.zip)
практика по формам
