### ISSUE TITLE
Publish Your Website!

### ISSUE THREAD

**Issue by ShahzadaMamatisaeva** [BrightBrainsKk/Section-3-Introduction-to-HTML#9]
Снять видео урок и загрузить код!

**Comment by alimbaeva** [comment]
сделала видео по записи на видео, о публикации сайта в гитхаб. Трудности встретились при но я поняла ошибки. https://www.youtube.com/watch?v=QQjfRdakq84 Можете пройти по этой ссылке и посмотреть.
